trigger:
  branches:
    include:
      - development
      - release/mainline
      - release/*

pr:
  autoCancel: 'true'
  branches:
    include:
      - development
      - release/mainline

variables:
  - group: cloud-kv
  - name: buildConfiguration
    value: 'Release'
  - name: DOCKER_REPOSITORY
    value: $(AWS-ACCOUNT-ID).dkr.ecr.$(AWS_REGION).amazonaws.com/raiha
  - name: stage_name
    ${{ if eq( variables['Build.SourceBranch'], 'refs/heads/release/mainline' ) }}: 
      value: 'production'
    ${{ if and(startsWith( variables['Build.SourceBranch'], 'refs/heads/release/' ), ne( variables['Build.SourceBranch'], 'refs/heads/release/mainline' ) ) }}:
      value: 'staging'
    ${{ if eq( variables['Build.SourceBranch'], 'refs/heads/development' ) }}:
      value: 'development'

stages:
- stage: Initialize
  dependsOn: []
  pool:
    vmImage: ubuntu-latest
  jobs: 
    - job: GitVersion
      steps:
        - task: gitversion/setup@0
          displayName: Install GitVersion
          inputs:
            versionSpec: '5.x'

        - task: gitversion/execute@0
          displayName: Execute GitVersion
          inputs:
            updateAssemblyInfo: true

- stage: Infrastructure
  dependsOn: []
  pool:
    vmImage: ubuntu-latest
  jobs:
    - job: Terraform
      steps:
        - task: TerraformInstaller@0
          displayName: Install Terraform
          inputs:
            terraformVersion: 'latest'

        - powershell: cd terraform\infrastructure && terraform init -backend-config="token=$(TERRAFORM_TOKEN)"
          displayName: Terraform Init

        - powershell: cd terraform\infrastructure && terraform plan -var $(TF_VAR_1) -var $(TF_VAR_2) -out "plan.terra"
          displayName: Terraform Plan
          env:
            AWS_ACCESS_KEY_ID: $(AWS-ACCESS-KEY-ID)
            AWS_SECRET_ACCESS_KEY: $(AWS-SECRET-ACCESS-KEY)
            AWS_REGION: $(AWS_REGION)
      
        - powershell: cd terraform\infrastructure && terraform apply "plan.terra"
          displayName: Terraform Apply

- stage: Build
  condition: succeeded()
  dependsOn:
    - Initialize
    - Infrastructure
  pool:
    vmImage: ubuntu-latest
  jobs:
    - job: Build
      steps:
        - task: UseDotNet@2
          displayName: Use NET6.0
          inputs:
            packageType: 'sdk'
            version: '6.0.x'
            includePreviewVersions: true

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            configuration: $(buildConfiguration)

        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: 'test'

        - task: Docker@2
          displayName: Build Docker Image
          inputs:
            repository: $(DOCKER_REPOSITORY)
            command: 'build'
            Dockerfile: 'Raiha/Dockerfile'
            buildContext: '**'
            tags: |
              $(Build.BuildNumber)

        - powershell: |
            aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS-ACCOUNT-ID).dkr.ecr.$(AWS_REGION).amazonaws.com
          displayName: Docker Login
          env:
            AWS_ACCESS_KEY_ID: $(AWS-ACCESS-KEY-ID)
            AWS_SECRET_ACCESS_KEY: $(AWS-SECRET-ACCESS-KEY)

        - task: Docker@2
          displayName: Push Docker Image
          inputs:
            repository: $(DOCKER_REPOSITORY)
            command: 'push'
            tags: |
              $(Build.BuildNumber)

- stage: Deploy
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn:
    - Build
  pool:
    vmImage: ubuntu-latest
  jobs:
    - job: Terraform
      steps:
        - task: TerraformInstaller@0
          displayName: Install Terraform
          inputs:
            terraformVersion: 'latest'

        - powershell: echo $(stage_name)
          displayName: Print Stage Name

        - powershell: cd terraform/deployment && ./init.ps1
          displayName: Pre-requisites
          env:
            TERRAFORM_TOKEN: $(TERRAFORM_TOKEN)

        - powershell: cd terraform/deployment && terraform workspace select $(stage_name)
          displayName: Workspace

        - powershell: cd terraform/deployment && terraform init -backend-config="token=$(TERRAFORM_TOKEN)"
          displayName: Init

        - powershell: cd terraform/deployment && terraform plan -var $(TF_VAR_1) -var $(TF_VAR_2) -var "image_tag=$(Build.BuildNumber)" -var "stage_name=$(stage_name)" -out "plan.terra"
          displayName: Plan
          env:
            AWS_ACCESS_KEY_ID: $(AWS-ACCESS-KEY-ID)
            AWS_SECRET_ACCESS_KEY: $(AWS-SECRET-ACCESS-KEY)
            AWS_REGION: $(AWS_REGION)
            AWS_DEFAULT_REGION: eu-central-1
      
        - powershell: cd terraform/deployment && terraform apply "plan.terra"
          displayName: Apply
