# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - development
  - release/mainline
  - release/*

pr:
  - development
  - release/mainline

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
  - task: gitversion/setup@0
    displayName: Install GitVersion
    inputs:
      versionSpec: '5.7.0'

  - task: gitversion/execute@0
    displayName: Execute GitVersion
    inputs:
      updateAssemblyInfo: true

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.x'
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      configuration: $(buildConfiguration)

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'

  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'

  - powershell: dotnet tool update -g Amazon.Lambda.Tools

  - powershell: cd terraform && terraform init -backend-config="token=$(TERRAFORM_TOKEN)"

  # - powershell: cd terraform && terraform plan -var $(TF_VAR_1) -var $(TF_VAR_2)

  - task: Docker@2
    inputs:
      command: 'build'
      Dockerfile: 'Raiha.Web/Dockerfile'
      buildContext: '**'