trigger:
  - development
  - release/mainline
  - release/*

pr:
  - development
  - release/mainline

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
  - task: gitversion/setup@0
    displayName: Install GitVersion
    inputs:
      versionSpec: '5.7.0'

  - task: gitversion/execute@0
    displayName: Execute GitVersion
    inputs:
      updateAssemblyInfo: true

  - task: UseDotNet@2
    displayName: Use NET6.0
    inputs:
      packageType: 'sdk'
      version: '6.0.x'
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      configuration: $(buildConfiguration)

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: 'test'

  - task: TerraformInstaller@0
    displayName: Install Terraform
    inputs:
      terraformVersion: 'latest'

  - powershell: dotnet tool update -g Amazon.Lambda.Tools
    displayName: Install Amazon Lambda Tools

  - powershell: cd terraform && terraform init -backend-config="token=$(TERRAFORM_TOKEN)"
    displayName: Terraform Init

  - powershell: cd terraform && terraform plan -var $(TF_VAR_1) -var $(TF_VAR_2) -target="aws_ecr_repository.ecr_raiha"
    displayName: Terraform Plan

  - task: Docker@2
    displayName: Build Docker Image
    inputs:
      command: 'build'
      Dockerfile: 'Raiha.Web/Dockerfile'
      buildContext: '**'